apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.12.1
    helm:
      valuesObject:
        serviceAccount:
          name: "external-secrets"
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::495599749247:role/external_secrets-role-ci-dev-green20250110162358914800000001
